package com.example.movieapp.Movie;

public enum Genre {
    ALL, ACTION, ADVENTURE, DRAMA, THRILLER, HORROR, ANIMATION, ROMANCE, COMEDY, BIOGRAPHY, FANTASY, SCIENCE_FICTION, CRIME, MYSTERY, FAMILY, WESTERN
}
